### ISSUE TITLE
Container based deployment

### ISSUE THREAD

**Issue by betatim** [everware/everware#101]
Create a container and related config files to deploy `everware` itself inside a container. This would drastically reduce the setup instructions and generally make life easier for new people wanted to try it out.

The [`tmpnb`](https://github.com/jupyter/tmpnb#quick-start) instructions could serve as a starting point.

To complete this we need several things:
- a container in which `everware` itself can run, potentially inherit [`FROM jupyter/jupyterhub`](https://github.com/jupyter/jupyterhub/blob/master/Dockerfile)
- setup auto building of this container on docker hub
- exercise the container in our travis runs to make sure `everware` starts inside it
- instructions for `README.md` to run locally
- instructions for the modifications needed to run with a docker swarm(?)
- example how to deploy to [getcarina.com](//getcarina.com) (?)

Should be done in several PRs

**Comment by betatim** [comment]
A related issue #43

**Comment by anaderi** [comment]
do you know a good way how to deploy your app on getcarina with any port accessible from the outside?

**Comment by betatim** [comment]
Last time I started a webserver on getcarina.com it was accessible from the outside world. Don't think I had to do anything special. Or do you mean what to do if you don't know the port number(s) to map when the container starts? For this I'd try `--net=host`.

**Comment by anaderi** [comment]
covered by #195
