### ISSUE TITLE
handle existing container properly

### ISSUE THREAD

**Issue by anaderi** [everware/everware#116]
once user launches everware with repo link, and he/she has a stopped container of his own from the previous launch (named jupyterhub-{username}), old container is started instead of a new one (even if image created is newer than image that was used to create an old one). This behavious is malicious since:
1. user doesn't see the difference in the container contents
2. if user had a bug in Dockerfile since last time, this bug persists and container doesn't start. and there is no way to fix for user unless admin `docker rm` this container
3. (minor) if user had a good running container from previous run of everware, he still may not access it since Jupyterhub authenticates containers by cookies (JPY_COOKIE_NAME) and cookies between runs may not match. User can fix it by stopping old container manually via control panel.

this issues mainly disappointing due to 2. 1 and 3 happen only if everware had been restarted without stopping/removing of running containers. 

Suggested behaviour: notify user that previous container exists and ask him/her if everware should reuse it or create a new one.

**Comment by betatim** [comment]
Do you understand why the container isn't stopped and rebuilt even though the hash has changed? Maybe the right question is why the old image is used instead of the new one.

**Comment by astiunov** [comment]
Because `dockerspawner` uses the existing container and doesn't take into account if the image is updated

**Comment by betatim** [comment]
We had this bug a while ago, and the solution was to make sure the container is not only stopped but also removed. This used to (like in the stoneage that long ago) require a modified version of jhub. I can take a closer look (in a week 😢).

Can you think of a usecase where you want to re-use a stopped container instead of always building the container "fresh" from the image?

**Comment by kazeevn** [comment]
I'm currently having `https://github.com/yandexdataschool/REP_tutorial` stuck on `Adding to proxy` - probably related to the issue,

**Comment by anaderi** [comment]
@kazeevn , the reason is the same as before - your previous container hasn't started properly:

> [C 2016-04-22 22:17:12.473 SingleUserNotebookApp application:77] Bad config encountered during initialization:
> [C 2016-04-22 22:17:12.473 SingleUserNotebookApp application:78] No such notebook dir: '/root/analysis'
> The Jupyter HTML Notebook.

so it should be fixed with #117

**Comment by betatim** [comment]
When the container is being stopped, it should also be removed. If that isn't happening that is a bug in everware/jupyterhub. Has someone looked at the code path that leads to stopping the container and seen a reason why it doesn't also get removed?
