### ISSUE TITLE
redirect to spawn page

### ISSUE THREAD

**Issue by anaderi** [everware/everware#119]
as I stop everware instance gracefully, then start it again, and then open in the browser URL:

http://localhost:8000/hub/user/anaderi/tree

it says:

> Your server is starting up.
> This can take seconds or minutes, please be patient.
> You will be redirected automatically when it's ready for you.
> This page is updated automatically.

while in the logs it complains that no such container `anaderi-jupyter` :

but apparently nothing is being created. in logs:

```
[D 2016-04-28 00:33:13.714 Everware log:100] 304 GET /hub/user/anaderi/tree?get_logs=1 (anaderi@127.0.0.1) 8.00ms
[D 2016-04-28 00:33:16.217 Everware spawner:226] Getting container: jupyter-anaderi
[I 2016-04-28 00:33:16.221 Everware spawner:234] Container 'jupyter-anaderi' is gone
```

IMO, if there is no such container , it should redirect to 'spawn' page. 

PS hasn't checked other `user` pages, but probably those also need such redirection.

**Comment by astiunov** [comment]
Need to redirect if there is no build in progress and it's not failed
