### ISSUE TITLE
cannot save jupyter notebooks larger than 1M

### ISSUE THREAD

**Issue by anaderi** [everware/everware#121]
I run notebook from repo https://github.com/arogozhnikov/GW150914, and as I save changes, it complains that notebook is too large.

**Comment by astiunov** [comment]
Is it `jupyter` which complains? If so, it's nothing we can do, the problem with `jupyter` or `juperhub` I suppose.

**Comment by anaderi** [comment]
Jupyter if run without jupyter hub can easily handle such large notebooks

**Comment by betatim** [comment]
Odd that jupyterhub should have a different limit. Have you investigated where in jhub it enforces the limit/raises the error?

Sidenote: for `nteract` we also briefly discussed the size limit of notebooks and there the conclusion was that this isn't a hard limit more and "accidental" one.

**Comment by anaderi** [comment]
issue was on nginx-proxy side, that was running in front of everware. 
Default value of `client_max_body_size` is 1M.
Changed to 10M.
