### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by RaoOfPhysics** [everware/everware#130]
Include:

`source activate everware`

for actually activating your conda environment.

Will take care of it.

**Comment by RaoOfPhysics** [comment]
Sorry. :(

**Comment by astiunov** [comment]
For what? Good job :+1:

**Comment by RaoOfPhysics** [comment]
For not having made the PR myself. I completely forgot about it! But I'm glad it's added. :)

**Comment by astiunov** [comment]
I didn't notice that it's not yours :)
