### ISSUE TITLE
Everware not working

### ISSUE THREAD

**Issue by arogozhnikov** [everware/everware#153]
https://github.com/yandexdataschool/mlhep2016 
click on "run me @ everware". 

Immediate result: 

```
503: Proxy Target Missing
The upstream service is unavailable
configurable-http-proxy
```

(I am logged in)

**Comment by arogozhnikov** [comment]
Main page https://everware.rep.school.yandex.net also does not respond.

**Comment by anaderi** [comment]
http://www3.imperial.ac.uk/newsandeventspggrp/imperialcollege/naturalsciences/highenergyphysics/eventssummary/event_9-11-2015-14-23-22
