### ISSUE TITLE
upgrade to jupyterhub 0.6.1, dockerspawner 0.5.0

### ISSUE THREAD

**Issue by anaderi** [everware/everware#166]
check that after upgrading jupyterhub, dockerspawner everware still works

**Comment by igormusinov** [comment]
have updated packages. Correct everware.egg-info/requirements.txt 
   "jupyterhub>=0.50" and "docker-py>=1.7.2" , if not there will be mistakes.
I got `Error: 'Future' object is not iterable`

**Comment by anaderi** [comment]
erm... you should never touch everware.egg-info/\* it is something has been installed. only https://github.com/everware/everware/blob/master/requirements.txt
also you should never put '>=' (you never know how backward-compatible next version will be). only '=='. Still I don't get what you are saying. What can I help you with?

**Comment by igormusinov** [comment]
My upgraded everware doesn't work, yet. Maybe somebody has managed to successfully upgrade it?

**Comment by anaderi** [comment]
it was the task: make sure it works after upgrade )

**Comment by anaderi** [comment]
...or even to 0.7b

**Comment by astiunov** [comment]
Solved in #182
