### ISSUE TITLE
Changing license

### ISSUE THREAD

**Issue by betatim** [everware/everware#17]
I've been reading the ZeroMQ guide while on holiday, in particular http://zguide.zeromq.org/page:chapter6#toc5. Seems convincing, in particular the part where people make additions to the project in a fork (under the GPL) that can't be merged into the original.

What do you think?

I am not up to date with LGPL vs GPL, even saw AGPL recently somewhere.

**Comment by betatim** [comment]
Any thoughts @ibab @anaderi?

After some more thinking I might have changed my mind -> stick with BSD

**Comment by ibab** [comment]
I'm for sticking with BSD

**Comment by betatim** [comment]
I declare this solved, we stick with what we have.
