### ISSUE TITLE
everware logo

### ISSUE THREAD

**Issue by eamonnmag** [everware/everware#18]
This idea has a circle to indicate 'forever', and a code block inside for the software element. I'm not sure about the infinity sign, but I added it just because it looked ok.

![everware](https://cloud.githubusercontent.com/assets/282396/9785000/d459a1dc-57a6-11e5-94bf-9023672ae9c6.png)

**Comment by cranmer** [comment]
for the record:
- maybe not the ∞
- see also http://mybinder.org
- maybe logo could reference a similar badge associated to launching the everware repo.

**Comment by betatim** [comment]
I adopted the light background circle part as the logo for the github organisation. Thanks for making this @eamonnmag :tada:

Kyle has a point about the ∞ and `project-binder`. Regarding binder we are/I am doing some thinking whether `everware` is still needed. (Thoughts welcome)

The badge exists already (#10), but we lack the resources to host a large scale accessible-for-everyone-in-the-world `everware` instance.

**Comment by cranmer** [comment]
> Kyle has a point about the ∞ and project-binder. Regarding binder we are/I am doing some thinking whether everware is still needed. (Thoughts welcome)
> 
> Would it help to have a short voice/video  discussion with some like-minded folks about this issue?

**Comment by betatim** [comment]
Yupp.com
