### ISSUE TITLE
Fast logout-login cycles are broken

### ISSUE THREAD

**Issue by betatim** [everware/everware#28]
When logging out and directly back in you get the old container.

This happens as destroying an existing container takes a finite amount of time. Currently the workaround is to wait ~10s after logging out before logging back in.

**Comment by anaderi** [comment]
closed by #45

**Comment by betatim** [comment]
I don't think this is fixed yet. It is related to how long it takes the hub to start removing containers etc.

**Comment by anaderi** [comment]
Aren't you shown page of previous container removal of you login prior to the completion? Will check a bit later.

**Comment by betatim** [comment]
When I did a fast logout->login on @ibab's instance on Sunday I got to see
the container that was about to be deleted. Which thinking about it now is
what we want. No containers get deleted when you press logout ... so this
is closed ;)
