### ISSUE TITLE
Lower case all github usernames

### ISSUE THREAD

**Issue by betatim** [everware/everware#33]
We want 'Cranmer' to match 'cranmer' when doing github oauth. Thanks for finding this @cranmer :)

**Comment by cranmer** [comment]
Ok, now I can authenticate with GitHub.
I launched one of the demo notebooks, but had to leave home before it was ready.
Went to work with a  switch of network and now when I try to connect I get 
500 : Internal Server Error

The URL is
https://everware.rep.school.yandex.net/hub/user/cranmer
same thing if I go here:
https://everware.rep.school.yandex.net/

I thought maybe OAuth was confused b/c my IP changed, so I restarted browser but I still get 500 error.

I just noticed that 
https://everware.rep.school.yandex.net/hub/user/Cranmer
(with the capital C) 
shows me the evernote homepage

So maybe the error is connected to the lowercase issue

Kyle

**Comment by betatim** [comment]
Is there a logout link (bottom right) on the error page? If not we need to add it.

Try visiting https://everware.rep.school.yandex.net/hub/logout or https://everware.rep.school.yandex.net/logout and wait 10s before signing in again.

At what point did you walk away: after sign-in or after clicking launch?

**Comment by betatim** [comment]
re-reading your comment I deduce you left after launching a notebook right?

**Comment by cranmer** [comment]
That's right. Thanks!

**Comment by cranmer** [comment]
I’ve tried both of the logout urls a few times (waiting in the middle), but they never resolve to a page.
Now I can’t see the homepage at
 https://everware.rep.school.yandex.ne https://everware.rep.school.yandex.net/hub/logoutt

I always get a 500 error.

Kyle

**Comment by betatim** [comment]
Trying to reproduce what you did here and struggling. Unfortunately I can't see the logs for the yandex instance. The brute force solution is to remove the cookies related to the domain, that is how the logins are done.

**Comment by cranmer** [comment]
I also tried in a different browser to avoid cookies, but also couldn't
login and got 500

Kyle
