### ISSUE TITLE
simultaneous image creation

### ISSUE THREAD

**Issue by anaderi** [everware/everware#41]
While several people are trying to create same image simultaneously often due to internal docker reasons (simultaneous building by several independent processes) some of them get 'error 500'
Everware should track progress of image creation and 
- there is no sense in creating same image for different people (as long as github repo and commit hash are the same)
- if image has been created by previous user, everware should just create container from that image for all the following creation attempts
- if image is being created, eveware should notify user and ask for some patience until image is created or failed

**Comment by betatim** [comment]
I had hoped these kinds of race conditions would be taken care of by the `dockerd`. Should definitely investigate and fix these.

**Comment by betatim** [comment]
Fixed by #45
