### ISSUE TITLE
Containerising everware and trying to set oauth against gitlab; running everware against a gitlab repo

### ISSUE THREAD

**Issue by Analect** [everware/everware#43]
@betatim or @anaderi 
First of all, thanks for this project.
I can see from the other issues, that work is planned for an update to everware.  I was trying to get the following working, as a containerised version of the README, initially against a github OAuth set-up.

Ultimately, I'm trying to get it working against a gitlab OAuth ... and to be able to feed a gitlab repo against which everware would then build an image and spin up a container on my behalf.  I'm not sure if this is possible yet .. in terms of whether the jupyter/oauthenticator needs to get extended to include gitlab and whether there are any other hurdles that would prevent this type of workflow from working.  Perhaps you might offer some guidance.

In an effort to containerise everware for testing, my starting point was to use the regularly built jupyter/jupyterhub:latest image from docker hub. I know it's not good practice to extend an image by direct installs onto a container .. but this is a feasibility test, after all.

I ran up the [jupyter/jupyterhub](https://github.com/jupyter/jupyterhub/blob/master/Dockerfile) image initially using:
`docker run -d -p 8000:8000 --name everware jupyter/jupyterhub jupyterhub`

I then entered that container (I user a `docker-enter` solution to do this ... but you can also use `docker exec`) ... where the already installed code-base for jupyterhub is at `/srv/jupyterhub` and continued with the everware README ... cloning dockerspawner to `/src/dockerspawner` and installing ... 

...and cloning everware to `/srv/everware` and installing as per pip. I used the main everware/everware repo ... however, I notice that the anaderi/everware repo has had more recent activity ... so perhaps I should be using this?  Also, obviously the everware repo includes a package.json and bower.json file ... but I didn't do anything about installing these (as there's nothing in the README to suggest that)... and I was also assuming that all relevant installations would have been done as part of the original jupyter/jupyterhub image build process.  Is this correct? 

Since I wanted to get this initially working with Github as an OAuth provider... I followed the set-up instructions for that ... adding credentials to env.sh and sourcing it.

```
export GITHUB_CLIENT_ID='54579xxxxx'
export GITHUB_CLIENT_SECRET='49c4d9d9xxxxx'
export OAUTH_CALLBACK_URL="http://localhost:8000/hub/oauth_callback"
```

The `\srv\everware\jupyterhub_config.py` file looks like this: https://gist.github.com/Analect/977e920b4231a0dbbb25

I played around with this a bit to try to get it to work ... hence a few commented out settings. On line 11, I changed to `everware.CustomDockerSpawner` as I didn't anticipate I would be using swarm. I added in the IP of the EC2 machine I'm trying to get this working on in lines 17 and 18. Incidentially, I'm using the same machine to host the GitLab that I ultimately want this to work against. I added my own github username in line 23 .. where I think you previously had various authors of gitlab ... lines 21 and 22 were my attempts to get the authentication working .. when the everware.GitHubOAuthenticator was failing.  The only other setting I changed was line 31, which I set to false (commenting out line 29) as I'm running this from linux.

With these various installations added to the base jupyter/jupyterhub image, I ran:
`docker commit everware everware/everware:0.2` ... so just converting the extended container back as an image.

I then ran:
`docker run -d -p 8000:8000 --name everware everware/everware:0.2 jupyterhub -f /srv/everware/jupyterhub_config.py --no-ssl`
... over-riding the jupyterhub command from the original jupyter/jupyterhub build by pointing to the /srv/everware/jupyterhub_config.py file instead.

If I navigate to the ec2 instance port 8000, I get:

![image](https://cloud.githubusercontent.com/assets/4063815/13371686/30a98652-dd24-11e5-8c5b-2e5c93933df8.png)

... however, I can't get the authentication to work.  Does this screen above suggest that the right jupyterhub_config is being picked up ... or should the screen I'm seeing be more like this: https://everware.rep.school.yandex.net/hub/login

Any pointers you have how I might get the basic set-up with Github up and running ... and then move on to set up against Gitlab would be much appreciated. Thanks.

**Comment by betatim** [comment]
A docker'ised version of everware would be super useful to have (there probably is an issue on that somewhere even)! I will read and follow along your description later today.

I had a quick look at your `jupyterhub_config.py` and the OAUTH callback link should be the IP of your ec2 instance, not localhost (are you running a jupyter notebook on localhost:8000 of your local machine by any chance? That would explain the login screen)

If you are setting yourself up from scratch now, take a look at #40 which needs some review and should catch `everware` up with the most recent `jupyterhub`

**Comment by betatim** [comment]
(I'd even go as far as merging #40 locally/in the container instead of using what is in master)

**Comment by betatim** [comment]
github vs gitlab: should make no difference. In principle any OAUTH provider should work and where the repo is hosted shouldn't matter (there might be hardcoded paths/names but those should be considered bugs). What you need to provide in the Git repo URL form is a URL that `git clone <url>` understands.

**Comment by Analect** [comment]
Thanks @betatim 
I'll try to work through your suggestions.

**Comment by Analect** [comment]
@betatim 
I've spent some time today trying to get this to work ... there are a number of implementations I was looking at that 'containerize' jupyterhub and then permit containers to be launched from that container ... something that would be nice to get working with everware. I think I'm closer than before ... I'll document what I've done, but perhaps you or one of the team can throw an eye over this.

First up, the other implementations that offer a good starting point:
a) https://github.com/ptimof/docker-jupyter/blob/master/5-jupyterhub/jupyterhub_config.py ... which is a derivation from ...
b) https://github.com/compmodels/jupyterhub/blob/master/jupyterhub_config.py ... where they are using a more complex set-up, including swarm, documented [here](https://developer.rackspace.com/blog/deploying-jupyterhub-for-education)
c) https://github.com/Unidata/Unidata-Dockerfiles/blob/master/jupyterhub/jupyterhub_config.py, where they are using their own [**nesteddockerspawner.NestedDockerSpawner**](https://github.com/Unidata/Unidata-Dockerfiles/blob/master/jupyterhub/nesteddockerspawner.py) class.

My approach was to:
(i) Run the dockerfile on https://github.com/jupyter/jupyterhub:
`docker build -t jupyter/jupyterhub:0.5.0 .`
(ii) use the above as a base to add in and install the latest master dockerspawner and everware repos. I'm feeding in an 'env' file (with github credentials for oauth as well as the jupyterhub_config.py file with _docker run_ ..see lower down

```
# in everware/jupyterhub directory, run docker build -t jupyter/jupyterhub:0.5.0 .
# now use that to seed this installation for everware
FROM jupyter/jupyterhub:0.5.0

WORKDIR /srv

# having cloned the latest dockerspawner from jupyter/dockerspawner into everware/dockerspawner, install it
COPY /dockerspawner/ /srv/dockerspawner
WORKDIR /srv/dockerspawner/
RUN /opt/conda/bin/pip install -r requirements.txt
RUN /opt/conda/bin/python setup.py install

# now do the same for everware itself
WORKDIR /srv
COPY /everware/ /srv/everware
WORKDIR /srv/everware/
RUN /opt/conda/bin/pip install -r requirements.txt
RUN /opt/conda/bin/python setup.py install

WORKDIR /srv/jupyterhub/

EXPOSE 8000

ONBUILD ADD jupyterhub_config.py /srv/everware/jupyterhub_config.py
CMD ["jupyterhub", "-f", "/srv/everware/jupyterhub_config.py"]
```

With this Dockerfile in place, I run:
`docker build -t everware/everware:0.3 .` ... disregard my versioning ... just my own way of keeping track.

This was the latest [jupyterhub_config.py](https://gist.github.com/Analect/fb186b512ac179ff5062) I've been playing with. There are lots of commented out lines ... as I tried all sorts of iterartions to get this to work.

With my everware/everware:0.3 image from above, I then run:

`docker run -d -p 8000:8000 -v /var/run/docker.sock:/var/run/docker.sock --net=host --name everware --env-file /home/ubuntu/everware/env everware/everware:0.3 jupyterhub -f /home/ubuntu/everware/jupyterhub_config.py --no-ssl`

I'm not sure whether --net=host is required still ... and I'm passing the --no-ssl, as I'm initially looking to try to get this everware hosted on http.

I'm clearly missing various things here.  Perhaps those various projects I've linked to above are not exactly on the right track, since they are concerned with launching multi-user notebook environments ... but their reliance on jupyterhub ... and their approach in terms of containerising jupyterhub, which itself can then spin up containers I thought was relevant for an everware that would be containerised and able to spin up containers/generate images.

Thanks for your input/pointers ...

**Comment by betatim** [comment]
Sorry for the very slow response. What you posted above looks reasonable. Do you have some log output as to what happens when you run this?

One thing I can think of off the top of my head is that maybe the docker spawner doesn't figure out by itself to use `/var/run/docker.sock`. Usually we configure it to take the info from the environment, so `DOCKER_HOST` and friends.

**Comment by BertrandNOEL** [comment]
I gave it a try, and I can connect to Everware, deploy a repository, and can see the container created, but I don't manage to get to the page of the deployed notebook.

My guess is that there is something wrong with the IP or link with the container. So I was playing with the parameter "c.Spawner.container_ip" in jupyterhub_config.py. If I leave the parameter by default (not present), Jupyter/Everware tells me that my container never showed up after 30s, so it kills it.
If I set the parameter  to the IP of my machine, I get a "500 : Internal Server Error", but with no logs to debug.

I changed a bit your Dockerfile Analect

``` bash
# in everware/jupyterhub directory, run docker build -t jupyter/jupyterhub:0.5.0 .
# now use that to seed this installation for everware
FROM jupyter/jupyterhub:0.5.0

WORKDIR /srv

# having cloned the latest dockerspawner from jupyter/dockerspawner into everware/dockerspawner, install it
COPY /dockerspawner/ /srv/dockerspawner
WORKDIR /srv/dockerspawner/
RUN /opt/conda/bin/pip install -r requirements.txt
RUN /opt/conda/bin/python setup.py install

# now do the same for everware itself
WORKDIR /srv
COPY /everware/ /srv/everware
WORKDIR /srv/everware/
RUN /opt/conda/bin/pip install -r requirements.txt
RUN /opt/conda/bin/python setup.py install

RUN /opt/conda/bin/python setup.py js
RUN /opt/conda/bin/python setup.py css

EXPOSE 8000

ENTRYPOINT ["jupyterhub", "-f", "/srv/everware/jupyterhub_config.py"]
```

I run the container with the following command:

``` bash
docker run --rm -it --name everware-docker \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $PWD/jupyterhub_config.py:/srv/everware/jupyterhub_config.py \
    --env-file=env \
    -p 8000:8000 \
    everware-docker --no-ssl --debug
```

My env file

``` bash
GITHUB_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxx
GITHUB_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
OAUTH_CALLBACK_URL=http://xxx.xxx.xxx.xxx:8000/hub/oauth_callback
EVERWARE_WHITELIST=whitelist.txt
```

My jupyterhub_config.py file

``` python
import os
import everware
import jupyterhub.handlers.pages
import jupyterhub.handlers.base

c = get_config()

# spawn with custom docker containers
c.JupyterHub.spawner_class = 'everware.CustomDockerSpawner'
#c.JupyterHub.spawner_class = 'everware.CustomSwarmSpawner'

# The docker instances need access to the Hub, so the default loopback port doesn't work:
# (IP addrress setting is overriden by command line argument at Makefile)
#ip_addr = '127.0.0.1'
#c.JupyterHub.hub_ip = ip_addr
#c.JupyterHub.hub_api_ip = ip_addr

authenticator = everware.GitHubOAuthenticator
c.JupyterHub.authenticator_class = '%s.%s' % (authenticator.__module__, authenticator.__name__)
whitelist_file = os.environ['EVERWARE_WHITELIST']
whitelist_handler = everware.DefaultWhitelistHandler(whitelist_file, c, authenticator)
c.GitHubOAuthenticator.oauth_callback_url = os.environ['OAUTH_CALLBACK_URL']
c.GitHubOAuthenticator.client_id = os.environ['GITHUB_CLIENT_ID']
c.GitHubOAuthenticator.client_secret = os.environ['GITHUB_CLIENT_SECRET']
# c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'
# c.Spawner.tls = True
# Set to False when running docker directly (i.e. on Linux)
c.Spawner.tls = False
c.Spawner.debug = True
c.Spawner.start_timeout = 1000
c.Spawner.remove_containers = True
c.Spawner.tls_assert_hostname = False
c.Spawner.use_docker_client_env = True

c.JupyterHub.data_files_path = 'share'
c.JupyterHub.template_paths = ['share/static/html']

# change this to the ip that `boot2docker ip` or
# `docker-machine ip <vm_name>`tells you if
# you use boot2docker/a VM, otherwise remove the line
c.Spawner.container_ip = 'xxx.xxx.xxx.xxx'
```

**Comment by BertrandNOEL** [comment]
Oh, I was missing 3 parameters (JupyterHub.hub_ip, JupyterHub.hub_api_ip, DockerSpawner.hub_ip_connect), and port 8081.
Now I have it working on my setup: Everware in a container, and creating its container on the same machine. I'll now try to deploy it on a machine, and create containers on another.

``` python
import os
import everware
import jupyterhub.handlers.pages
import jupyterhub.handlers.base

c = get_config()

# spawn with custom docker containers
c.JupyterHub.spawner_class = 'everware.CustomDockerSpawner'
#c.JupyterHub.spawner_class = 'everware.CustomSwarmSpawner'

# The docker instances need access to the Hub, so the default loopback port doesn't work:
# (IP addrress setting is overriden by command line argument at Makefile)
#ip_addr = '127.0.0.1'
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.hub_api_ip = '0.0.0.0'

authenticator = everware.GitHubOAuthenticator
c.JupyterHub.authenticator_class = '%s.%s' % (authenticator.__module__, authenticator.__name__)
whitelist_file = os.environ['EVERWARE_WHITELIST']
whitelist_handler = everware.DefaultWhitelistHandler(whitelist_file, c, authenticator)
c.GitHubOAuthenticator.oauth_callback_url = os.environ['OAUTH_CALLBACK_URL']
c.GitHubOAuthenticator.client_id = os.environ['GITHUB_CLIENT_ID']
c.GitHubOAuthenticator.client_secret = os.environ['GITHUB_CLIENT_SECRET']
# c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'
# c.Spawner.tls = True
# Set to False when running docker directly (i.e. on Linux)
c.Spawner.tls = False
c.Spawner.debug = True
c.Spawner.start_timeout = 1000
c.Spawner.remove_containers = True
c.Spawner.tls_assert_hostname = False
c.Spawner.use_docker_client_env = True

c.JupyterHub.data_files_path = 'share'
c.JupyterHub.template_paths = ['share/static/html']

# change this to the ip that `boot2docker ip` or
# `docker-machine ip <vm_name>`tells you if
# you use boot2docker/a VM, otherwise remove the line
c.Spawner.container_ip = 'xxx.xxx.xxx.xxx'
c.DockerSpawner.hub_ip_connect = 'xxx.xxx.xxx.xxx'
```

``` bash
docker run --rm -it --name everware-docker \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $PWD/jupyterhub_config.py:/srv/everware/jupyterhub_config.py \
    --env-file=env \
    -p 8000:8000 \
    -p 8081:8081 \
    everware-docker --no-ssl --debug
```

**Comment by betatim** [comment]
Thanks a lot for the detailed information.

edit: just saw your update, so what I wrote is not needed anymore, will leave it just in case.

---

Are you on linux or do you use a virtual machine for docker?

What do the logs in the everware server container say? Can you grab the logs from the container that everware starts for your repo as well?

`c.Spawner.container_ip` should be the IP at which the container started by everware will be reachable. The other part that is a bit tricky to get right is that the container started for your repo has to be able to talk to the hub as well. I see that in your config `c.JupyterHub.hub_ip`is commented out.

We recently re-organised the config files which should make them a bit more modular and as a result might have docs out of sync with reality.

I will have some time later this afternoon to follow your steps and give better feedback

**Comment by betatim** [comment]
We want to start collecting examples of how to deploy `everware`, when you have something that you are happy with would you like to contribute your setup/info as a PR? That would be super for us.

**Comment by BertrandNOEL** [comment]
Yes sure. My goal is to deploy it on Swarm. I'll begin by making it talk to a remote Docker daemon, and then will try on Swarm. I'll do the doc for the 3 cases after that (I won't have time next week, so it will be for the week after)

**Comment by betatim** [comment]
That would be super cool. In principle it should "just work" with swarm. Especially if you have a working setup for Mac. @anaderi has some experience as he looks after https://everware.rep.school.yandex.net which is backed by a swarm.

**Comment by BertrandNOEL** [comment]
I rebased my changes on top of the new way config files are done, and I just did a pull request.

I managed to have an Everware container, created on a specific machine, and this Everware container creates users container on a Swarm cluster.
I wanted to put as well the Everware container on the Swarm cluster, but it cannot be easily done, because I don't know the host on which the container will be scheduled. The IP is needed for the OAuth, and the "c.DockerSpawner.hub_ip_connect" params.

**Comment by betatim** [comment]
One option would be to use the affinity rules of swarm to tie the everware container to a certain node. Then you would know the IP in advance and could configure OAuth etc.

**Comment by BertrandNOEL** [comment]
Good idea. I tried it, it works

```
docker run -d -e constraint:node==swarm-node-name everware ...
```

**Comment by anaderi** [comment]
should be enough to say that gitlab has same API as github, and #195 to close this?
