### ISSUE TITLE
Remote global sprint

### ISSUE THREAD

**Issue by betatim** [everware/everware#44]
:construction: @ibab and @betatim will have a small sprint this weekend (March 5th and 6th) to hack on `everware`. :construction_worker: 

:video_camera: As everyone will be remote, we will appear.in: https://appear.in/everware as much as possible. :video_camera: 

Most likely we will have a short meeting on Friday evening (GMT) to coordinate. Suggestions for a time slot welcome.

:checkered_flag: The goal is to get closer to being ready for new contributors. This means if you are a new contributor, you are very very welcome to join. However you will have to give us the benefit of the doubt with a lot of things. :checkered_flag: 

Take a look at the ROADMAP (#39) and see mozillascience/working-open-workshop#46 for some details/admin stuff on the project itself.

To start thinking, here some topics to work on (post more below and I'll keep this list updated):
- [x] write one automated test
- [x] merge #40 
- [x] automatically run an automated test when a new PR is started
- [ ] make `everware-cli init` create a `Dockerfile`
- [ ] create one [persona](https://docs.google.com/presentation/d/1YO6caHS7Pmg_W1uRdN9_BqkKRM5bn47_ZInRtzuyfYA/edit)
- [ ] write a HiggsML solution example 

:white_check_mark:  Post below if you want to join in. You don't have to have time all weekend :smile: We understand if you need time for :zzz: or :runner: or :pizza: or :cocktail: or :family:

**Comment by anaderi** [comment]
- [ ] write a HiggsML solution example

**Comment by betatim** [comment]
Integrated in the list. Turns out I might not be able to dedicate the whole weekend to this. Will still try to be around though :cry:

**Comment by betatim** [comment]
Unsure when we will all have time at the same time tonight.

I will start working done the list from the top. Though I need someone who isn't me to merge #40 and chime in on the discussion there.

**Comment by anaderi** [comment]
If you are through with #40 I will merge it

**Comment by anaderi** [comment]
Also leave testing for me, I'm almost through with it

**Comment by anaderi** [comment]
Merged!

**Comment by betatim** [comment]
I think we can have two kinds of testing no? `phantomjs` for testing the web interface and unittests like they have in jupyterhub for testing some of the internal stuff.

**Comment by betatim** [comment]
@astiunov can you make a new PR to this repo?

**Comment by anaderi** [comment]
Fine! phantom is mine, rest is yours)

**Comment by astiunov** [comment]
@betatim, made a PR

**Comment by betatim** [comment]
Seems like everyone has things that they'd like to work on. I will probably start tomorrow morning during breakfast, then have to do some chores and sport and come back around lunch time.

**Comment by ibab** [comment]
I'll start tomorrow during/after breakfast as well.

**Comment by betatim** [comment]
Good morning all.

Currently I am looking at using a docker container for deploying everware. Would be a nice way to document the setup procedure, run CI, etc.

Are you all on lhcb.slack.com or where could we hang out to chat?

**Comment by anaderi** [comment]
Morning! ) maybe use gitter.am or appear.in? since astiunov@ is not at lhcb

**Comment by betatim** [comment]
https://gitter.im/everware/everware

**Comment by betatim** [comment]
Issues closed: #27 #29 #32 #10 #41 
PRs merged: #57 #53 #55 #54 #48 #52 #50 #47 #45 #40 

:tada: :balloon: Good :construction: everyone on :ship:ing a bunch of improvements!

Still outstanding is #49 which will allow users to store their work on github with the push of a button. This will be huge.
