### ISSUE TITLE
Getting on collaborate

### ISSUE THREAD

**Issue by betatim** [everware/everware#56]
We should follow the secret instructions from the MSL guys and get up on https://www.mozillascience.org/collaborate

**Comment by anaderi** [comment]
do we need to qualify for that somehow first?

**Comment by betatim** [comment]
I think right now it is invite only but we have an invite.

**Comment by anaderi** [comment]
So we need a piece of text, an image and that's it?

**Comment by betatim** [comment]
Think about what kind of new people we would like to attract or what we'd
like help with -> create some personas for devs joining. I'd suggest trying
to find a designer type for even nicer UI/frontend. We have a lot of coding
skills and the next coding stuff I see on the horizon is writing tests and
docs (which we need to do ourselves).

**Comment by betatim** [comment]
Submitted and waiting for @acabunoc to do her magic. Follow mozillascience/working-open-workshop#46 if you want to track this

**Comment by abbycabs** [comment]
I'm on it! this week!

**Comment by betatim** [comment]
:notes: this has been done.
