### ISSUE TITLE
indication of 'stop container' progress after quick logout/login

### ISSUE THREAD

**Issue by anaderi** [everware/everware#69]
scenario: 
- user logs in
- spawns a container (say by https://github.com/everware/everware-dimuon-example)
- user goes to control panel & presses 'Stop my server'
- user quickly logs out and 'signs in' again
- he is shown an empty spawn page with no indicators of container deletion and buttons for starting new one. 

Is it possible to show 'stopping container' in case he logs in before container is completely destroyed?

**Comment by astiunov** [comment]
The reason is this jupyterhub's update: https://github.com/jupyter/jupyterhub/commit/82643adfb6f7eea74abcad8d800120eff640ed94

**Comment by betatim** [comment]
To me it makes sense to consider a container that is stopping as not running. If there is no running container we should see a start button though.
