### ISSUE TITLE
upon creation of a second image, name of the 1st one is taken

### ISSUE THREAD

**Issue by anaderi** [everware/everware#76]
scenario:
1. - user logs in
2. - user creates container by https://github.com/everware/everware-dimuon-example, 
3. - everware creates image, container and starts it fine
4. - user stops container in control panel
5. - user creates another container by another URL https://github.com/anaderi/openml-demo,
6. - everware picks as a name of image from 4 but recreates it with contents of new repo
7. - as everware starts container , user sees contents of image created before (4!) :dizzy_face:

**Comment by betatim** [comment]
Trying to solve this in #51

**Comment by anaderi** [comment]
fixed
