### ISSUE TITLE
Reduce output from frontend tests when they pass

### ISSUE THREAD

**Issue by betatim** [everware/everware#82]
Thoughts on reducing the amount of text generated by the tests when they are successful? Right now it prints a lot of text which is distracting/not interesting when the tests pass. Absolutely needed when the tests fail though. Would be nice to have a smart way to only print what is relevant to a failure. Ideas?

**Comment by betatim** [comment]
Implementing #103 will make this easier.

**Comment by astiunov** [comment]
Was partially implemented in #117. Now server's log isn't printed if tests are successful. However, I don't know how to select only relevant to a failure output. I prefer to have an entire log

**Comment by betatim** [comment]
There is no way to make use of `nose` infrastructure for this? Normally `nose` captures the stdout and suppresses it. Maybe we need to move starting of `everware-server` into the setup/teardown of the tests to get that.
