### ISSUE TITLE
support for checking-out particular branch or commit of github repo

### ISSUE THREAD

**Issue by anaderi** [everware/everware#96]
ie user should be able to point to specific version of the repository by appending
"@branch" or "@8234abc03" to repo URL
examples of valid URLs:

git://github.com/aladagemre/django-notification.git@2927346f4c513a217ac8ad076e494dd1adbf70e1
git://github.com/aladagemre/django-notification.git@cool-feature-branch
git://github.com/aladagemre/django-notification.git@v2.1.0

NB it should be treated with care while someone tries to fork repo -- branch 'everware' should be created that starts from particular tag/branch/commit specified in URL.

**Comment by betatim** [comment]
Can we use a URL format similar to the one used by github? So something like:

`https://github.com/USER/REPO/tree/BRANCH_OR_COMMIT`

means users could copy&paste the URL they see on github. GitLab uses the same schema. To fully support this feature the container has to cooperate as we clone the repo twice. Once outside to get the `Dockerfile` and then again from inside the container once it has started.

For `https` URLs I think we can't put a `@` at the end as it is used to encode `https://user:password@host` in the specs. We need to keep supporting this as this is the way to clone private repos

**Comment by anaderi** [comment]
1. I'd suggest to support both notations (https://github.com/USER/REPO/tree/BRANCH_OR_COMMIT and https://github.com/USER/REPO@BRANCH_OR_COMMIT) since the latter is kind of a standard now.
2. I'm not that confident people are willing to share their github passwords with us.  so it might be the case when they setup own instance of everware, but I'd put support of private repos into a separate issue not to clutter this PR

**Comment by betatim** [comment]
(Created #102 for private repo access discussion.)

Do you know if there is any plan to support either URL schema (or a third one??) in the `git` client any time soon?

[`pip` uses the repo@rev style links](https://pip.pypa.io/en/latest/reference/pip_install/#git) as well. We should detect this when the user enters such a URL and let them know that support for this depends on the container they are trying to launch.

Maybe another option is to add a extra field to our spawner form in which people can enter the SHA or branch name. This would be an optional field with a message saying that it has to be supported by the container you are trying to launch.

What do you think?

**Comment by anaderi** [comment]
looks like git is not going to support any URLs besides standard ones (http://www.kernel.org/pub/software/scm/git/docs/git-clone.html#URLS) and there are no issues on that in their repo (https://github.com/gitpython-developers/GitPython/) and no hint for anything besides basic command-line args of `clone` subcommand. 

It would be cool to have single field for the repo that would parse various forms of repo+specific pointer URLs (i.e. https://github.com/USER/REPO/tree/BRANCH_OR_COMMIT and git://github.com/aladagemre/django-notification.git@branch_or_commit), and keep 2 variables 'repo_url' and 'repo_pointer' and in the spawner upon 'git.clone' do 'cd dir' and 'git.checkout(repo_pointer)'. 
If having one field + parser is difficult to start with, we can have a separate field for repo_pointer.
Also we should pass additional environment variable to the container (JPY_REPOPOINTER) that should instruct spawner script within container to run `git checkout ...` before launching jupyter. 

additional complication is that if user checks out specific commit, HEAD becomes in detached state and changes can be committed back only if new branch is created. So either
- everware should create new branch 'everware-XXX' (where XXX is unique number) before commit. 
- or we should disable fork/push if HEAD is detached (one can check it by `git.status` method)
  For simplicity sake I'd vote for the latter case to start with.

in case repo_pointer is set to branch, forking this repository should also keep user in this branch.

Also we should display current git state (current branch/pointer and state (has something changes or not)) somewhere in the everware interface. Is it possible to display it in the topmost part of the window? or only in the home_handler?
